# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # - name: npm init
    #   run: npm init -y
        
    # - name: install dependencies
    #   run: npm install

    # - name: clean cache
    #   run: npm cache clean --force

    # - name: install -g
    #   run: npm install -g npm
    
    - name: install dependencies
      run: npm install

    - name: build
      run: npm run build
    
    - name: Deploy GH-Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: ./dist
        enable_jekyll: true
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
    
    - name: Deploy Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "brutuswear"
        email: "magnonta@gmail.com"
        dockerfile_directory: ./
        dockerfile_name: Dockerfile